### ISSUE TITLE
[Blue Burst] Opening the Party List while other players are doing a joinable Gov Quest which you haven't cleared yet kills the newserv process

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#436]
**Describe the bug**
Player 1 is doing Gov quest 3-1 while suddenly Player 2 connects to the game, Player 2 in the lobby goes to the counter to check the list of current available rooms, the list never opens and the whole newserv process is killed disconnecting all players in the game.

This only happens with Government Quests which are joinable if Player 1 loads for example quest 2-3 which is not joinable the crash wont happen. 

Likewise, if both players are able to play the quest, for example 1-1 the crash wont happen either. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Player 1 creates a new room and starts a later Gov Quest for example 2-1 or 3-1
2. After a while Player 2 which was in the lobby heads to the counter to open the list of current active rooms
3. Player 2 only has quest 1-1 available so should be able to see the Player 1 room greyed out in the list
4. The list never appears and both players get Error 100 and the whole newserv process ends too

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[roomCheckNewservKO.txt](https://github.com/fuzziqersoftware/newserv/files/14613823/roomCheckNewservKO.txt)

**backtrace**
```
Thread 1 "newserv" received signal SIGSEGV, Segmentation fault.
0x000000000044df81 in QuestFlagsForDifficulty::get(unsigned short) const ()
(gdb) bt
#0  0x000000000044df81 in QuestFlagsForDifficulty::get(unsigned short) const ()
#1  0x0000000000756038 in QuestAvailabilityExpression::FlagLookupNode::evaluate(QuestAvailabilityExpression::Env const&) const ()
#2  0x0000000000467466 in QuestAvailabilityExpression::evaluate(QuestAvailabilityExpression::Env const&) const ()
#3  0x00000000004619d4 in Client::evaluate_quest_availability_expression(std::shared_ptr<QuestAvailabilityExpression const>, unsigned char, unsigned char, unsigned long, bool) const ()
#4  0x0000000000461b6f in Client::can_see_quest(std::shared_ptr<Quest const>, unsigned char, unsigned char, unsigned long, bool) const ()
#5  0x000000000062c20d in Lobby::join_error_for_client(std::shared_ptr<Client>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) const ()
#6  0x000000000086c453 in void send_game_menu_t<(TextEncoding)6>(std::shared_ptr<Client>, bool, bool) ()
#7  0x000000000084e014 in send_game_menu(std::shared_ptr<Client>, bool, bool) ()
#8  0x00000000007c203d in on_08_E6(std::shared_ptr<Client>, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#9  0x00000000007d4edd in on_command(std::shared_ptr<Client>, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#10 0x00000000008a1daa in Server::on_client_input(Channel&, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#11 0x00000000004319e3 in Channel::dispatch_on_input(bufferevent*, void*) ()
#12 0x00007ffff7f6b299 in bufferevent_run_deferred_callbacks_locked (cb=<optimized out>, arg=0x7e6d770) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/bufferevent.c:167
#13 0x00007ffff7f76223 in event_process_active_single_queue (base=base@entry=0xcf89f0, activeq=0xc85220, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1720
#14 0x00007ffff7f77fdf in event_process_active (base=0xcf89f0) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1783
#15 event_base_loop (base=0xcf89f0, flags=0) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:2006
#16 0x00000000006565cb in a_run_server_replay_log::{lambda(Arguments&)#1}::operator()(Arguments&) const ()
#17 0x0000000000656b14 in a_run_server_replay_log::{lambda(Arguments&)#1}::_FUN(Arguments&) ()
#18 0x0000000000675319 in void std::__invoke_impl<void, void (*&)(Arguments&), Arguments&>(std::__invoke_other, void (*&)(Arguments&), Arguments&) ()
#19 0x000000000066a101 in std::enable_if<is_invocable_r_v<void, void (*&)(Arguments&), Arguments&>, void>::type std::__invoke_r<void, void (*&)(Arguments&), Arguments&>(void (*&)(Arguments&), Arguments&) ()
#20 0x0000000000660801 in std::_Function_handler<void (Arguments&), void (*)(Arguments&)>::_M_invoke(std::_Any_data const&, Arguments&) ()
#21 0x0000000000660047 in std::function<void (Arguments&)>::operator()(Arguments&) const ()
#22 0x0000000000641bad in main ()

```

```
0x000000000044df81 in QuestFlagsForDifficulty::get(unsigned short) const ()
(gdb) bt
#0  0x000000000044df81 in QuestFlagsForDifficulty::get(unsigned short) const ()
#1  0x0000000000756038 in QuestAvailabilityExpression::FlagLookupNode::evaluate(QuestAvailabilityExpression::Env const&) const ()
#2  0x0000000000467466 in QuestAvailabilityExpression::evaluate(QuestAvailabilityExpression::Env const&) const ()
#3  0x00000000004619d4 in Client::evaluate_quest_availability_expression(std::shared_ptr<QuestAvailabilityExpression const>, unsigned char, unsigned char, unsigned long, bool) const ()
#4  0x0000000000461b6f in Client::can_see_quest(std::shared_ptr<Quest const>, unsigned char, unsigned char, unsigned long, bool) const ()
#5  0x000000000062c20d in Lobby::join_error_for_client(std::shared_ptr<Client>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) const ()
#6  0x000000000086c453 in void send_game_menu_t<(TextEncoding)6>(std::shared_ptr<Client>, bool, bool) ()
#7  0x000000000084e014 in send_game_menu(std::shared_ptr<Client>, bool, bool) ()
#8  0x00000000007c203d in on_08_E6(std::shared_ptr<Client>, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#9  0x00000000007d4edd in on_command(std::shared_ptr<Client>, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#10 0x00000000008a1daa in Server::on_client_input(Channel&, unsigned short, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#11 0x00000000004319e3 in Channel::dispatch_on_input(bufferevent*, void*) ()
#12 0x00007ffff7f6b299 in bufferevent_run_deferred_callbacks_locked (cb=<optimized out>, arg=0x7e6d2a0) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/bufferevent.c:167
#13 0x00007ffff7f76223 in event_process_active_single_queue (base=base@entry=0xcf89f0, activeq=0xc85220, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1720
#14 0x00007ffff7f77fdf in event_process_active (base=0xcf89f0) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1783
#15 event_base_loop (base=0xcf89f0, flags=0) at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:2006
#16 0x00000000006565cb in a_run_server_replay_log::{lambda(Arguments&)#1}::operator()(Arguments&) const ()
#17 0x0000000000656b14 in a_run_server_replay_log::{lambda(Arguments&)#1}::_FUN(Arguments&) ()
#18 0x0000000000675319 in void std::__invoke_impl<void, void (*&)(Arguments&), Arguments&>(std::__invoke_other, void (*&)(Arguments&), Arguments&) ()
#19 0x000000000066a101 in std::enable_if<is_invocable_r_v<void, void (*&)(Arguments&), Arguments&>, void>::type std::__invoke_r<void, void (*&)(Arguments&), Arguments&>(void (*&)(Arguments&), Arguments&) ()
#20 0x0000000000660801 in std::_Function_handler<void (Arguments&), void (*)(Arguments&)>::_M_invoke(std::_Any_data const&, Arguments&) ()
#21 0x0000000000660047 in std::function<void (Arguments&)>::operator()(Arguments&) const ()
#22 0x0000000000641bad in main ()

```
**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/1e2dde2e-43e5-4002-816e-886352c34c14)

**Comment by fuzziqersoftware** [comment]
This has been fixed by dc36d2ae.
